export const COUNTRY_NAME_TO_ISO: Record<string, string> = {
  "United States": "US",
  "China": "CN",
  "Japan": "JP",
  "Germany": "DE",
  "India": "IN",
  "United Kingdom": "GB",
  "France": "FR",
  "Brazil": "BR",
  "Italy": "IT",
  "Canada": "CA",
  "Russia": "RU",
  "South Korea": "KR",
  "Australia": "AU",
  "Spain": "ES",
  "Mexico": "MX",
  "Indonesia": "ID",
  "Netherlands": "NL",
  "Saudi Arabia": "SA",
  "Turkey": "TR",
  "Switzerland": "CH",
  "Taiwan": "TW",
  "Poland": "PL",
  "Sweden": "SE",
  "Belgium": "BE",
  "Thailand": "TH",
  "Argentina": "AR",
  "Norway": "NO",
  "Austria": "AT",
  "Iran": "IR",
  "United Arab Emirates": "AE",
  "South Africa": "ZA",
  "Denmark": "DK",
  "Egypt": "EG",
  "Philippines": "PH",
  "Malaysia": "MY",
  "Singapore": "SG",
  "Vietnam": "VN",
  "Hong Kong": "HK",
  "Israel": "IL",
  "Ireland": "IE",
  "Pakistan": "PK",
  "Chile": "CL",
  "Finland": "FI",
  "Portugal": "PT",
  "Greece": "GR",
  "Kazakhstan": "KZ",
  "Peru": "PE",
  "Qatar": "QA",
  "New Zealand": "NZ",
  "Czech Republic": "CZ",
  "Romania": "RO",
  "Colombia": "CO",
  "Hungary": "HU",
  "Ukraine": "UA",
  "Kuwait": "KW",
  "Morocco": "MA",
  "Slovakia": "SK",
  "Ecuador": "EC",
  "Oman": "OM",
  "Puerto Rico": "PR",
  "Kenya": "KE",
  "Sri Lanka": "LK",
  "Ethiopia": "ET",
  "Dominican Republic": "DO",
  "Guatemala": "GT",
  "Luxembourg": "LU",
  "Myanmar": "MM",
  "Uzbekistan": "UZ",
  "Panama": "PA",
  "Bulgaria": "BG",
  "Uruguay": "UY",
  "Costa Rica": "CR",
  "Croatia": "HR",
  "Ivory Coast": "CI",
  "Lithuania": "LT",
  "Tanzania": "TZ",
  "Slovenia": "SI",
  "Serbia": "RS",
  "Azerbaijan": "AZ",
  "Ghana": "GH",
  "Jordan": "JO",
  "Tunisia": "TN",
  "Cameroon": "CM",
  "Uganda": "UG",
  "Bolivia": "BO",
  "Latvia": "LV",
  "Bahrain": "BH",
  "Estonia": "EE",
  "Paraguay": "PY",
  "Nepal": "NP",
  "El Salvador": "SV",
  "Cyprus": "CY",
  "Iceland": "IS",
  "Cambodia": "KH",
  "Zambia": "ZM",
  "Senegal": "SN",
  "Papua New Guinea": "PG",
  "Zimbabwe": "ZW",
  "Bosnia and Herzegovina": "BA",
  "Georgia": "GE",
  "Honduras": "HN",
  "Botswana": "BW",
  "Namibia": "NA",
  "Jamaica": "JM",
  "Mozambique": "MZ",
  "Palestine": "PS",
  "Malta": "MT",
  "Burkina Faso": "BF",
  "Mauritius": "MU",
  "Mali": "ML",
  "Albania": "AL",
  "Armenia": "AM",
  "Mongolia": "MN",
  "Trinidad and Tobago": "TT",
  "Madagascar": "MG",
  "Laos": "LA",
  "Nicaragua": "NI",
  "North Macedonia": "MK",
  "Moldova": "MD",
  "Kyrgyzstan": "KG",
  "Tajikistan": "TJ",
  "Haiti": "HT",
  "Gabon": "GA",
  "Benin": "BJ",
  "Rwanda": "RW",
  "Guinea": "GN",
  "Congo": "CG",
  "Chad": "TD",
  "Mauritania": "MR",
  "Brunei": "BN",
  "Niger": "NE",
  "Malawi": "MW",
  "Bahamas": "BS",
  "Montenegro": "ME",
  "Barbados": "BB",
  "Togo": "TG",
  "Maldives": "MV",
  "Fiji": "FJ",
  "Eswatini": "SZ",
  "Suriname": "SR",
  "Guyana": "GY",
  "Lesotho": "LS",
  "Bhutan": "BT",
  "Liberia": "LR",
  "Cabo Verde": "CV",
  "Djibouti": "DJ",
  "Gambia": "GM",
  "Saint Lucia": "LC",
  "Belize": "BZ",
  "Central African Republic": "CF",
  "Antigua and Barbuda": "AG",
  "Guinea-Bissau": "GW",
  "Solomon Islands": "SB",
  "Seychelles": "SC",
  "Grenada": "GD",
  "Comoros": "KM",
  "Saint Kitts and Nevis": "KN",
  "Vanuatu": "VU",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "Dominica": "DM",
  "Tonga": "TO",
  "Sao Tome and Principe": "ST",
  "Micronesia": "FM",
  "Palau": "PW",
  "Marshall Islands": "MH",
  "Kiribati": "KI",
  "Tuvalu": "TV",
  "Nauru": "NR",
  "Monaco": "MC",
  "Liechtenstein": "LI",
  "San Marino": "SM",
  "Andorra": "AD",
  "Vatican City": "VA",
};

export function getCountryIso(countryName: string): string | null {
  // Normalize input
  const normalized = countryName.trim();
  
  // Direct lookup
  if (COUNTRY_NAME_TO_ISO[normalized]) {
    return COUNTRY_NAME_TO_ISO[normalized];
  }

  // Case insensitive lookup
  const lower = normalized.toLowerCase();
  for (const [name, iso] of Object.entries(COUNTRY_NAME_TO_ISO)) {
    if (name.toLowerCase() === lower) {
      return iso;
    }
  }

  return null;
}
