-- Create table for storing Fintra FGOS snapshots
create table if not exists fintra_snapshots (
  id bigint generated by default as identity primary key,
  symbol text not null,
  date date not null default current_date,
  fgos_score int not null,
  fgos_breakdown jsonb not null,
  valuation_status text not null,
  ecosystem_score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Add a unique constraint to prevent duplicate snapshots for the same symbol on the same day
  constraint fintra_snapshots_symbol_date_key unique (symbol, date)
);

-- Enable Row Level Security (RLS)
alter table fintra_snapshots enable row level security;

-- Create policy to allow read access for everyone (or restrict as needed)
create policy "Enable read access for all users" on fintra_snapshots
  for select using (true);

-- Create policy to allow service role to insert/update (or specific users)
create policy "Enable insert/update for service role" on fintra_snapshots
  for all using (true) with check (true);
