-- Add 'id' column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'fintra_snapshots' AND column_name = 'id') THEN
        ALTER TABLE fintra_snapshots ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
END $$;

-- Add 'sector' column if it doesn't exist
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS sector TEXT;

-- Ensure other columns expected by the code exist
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS ticker TEXT;
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS fgos_score NUMERIC;
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS valuation_status TEXT;
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS valuation_score NUMERIC;
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS verdict_text TEXT;
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS calculated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE fintra_snapshots ADD COLUMN IF NOT EXISTS fgos_breakdown JSONB;
