-- Add missing columns to fintra_market_state
ALTER TABLE fintra_market_state
ADD COLUMN IF NOT EXISTS company_name TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS employees TEXT,
ADD COLUMN IF NOT EXISTS ceo TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS return_1y NUMERIC,
ADD COLUMN IF NOT EXISTS return_3y NUMERIC,
ADD COLUMN IF NOT EXISTS return_5y NUMERIC,
ADD COLUMN IF NOT EXISTS sector_percentiles JSONB;
